### ISSUE TITLE
Typespec says batch must always be empty map

### ISSUE THREAD

**Issue by eoinkelly** [appcues/batch_please#1]
The batch typespec is `@type batch :: %{}` (see https://github.com/appcues/batch_please/blob/master/lib/batch_please.ex#L185). This typespec is causing dialyzer to complain about my `batch_init/1` and `batch_add_item/2` callbacks because they don't return an _empty_ map. 

I think changing the typespec to `@type batch :: map()` would fix this. I'm happy to make a PR but I'm pretty new to dialyzer & elixir types so I wanted to sanity check that I haven't missed something obvious first. Thanks for your time.

**Comment by gamache** [comment]
Sorry I didn't see this until now!  You are correct, and I'll fix it in the next release.

**Comment by gamache** [comment]
Fixed in 0.5.0.  Thanks again!
